
version: "3.7"

services:

  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./conf/mysql-db/entrypoint
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ${PR_LOC_SRC:-./conf/mysql-db/entrypoint}
        target: ${PR_LOC_TGT:-/prom}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password123}
      MYSQL_USER: ${MYSQL_USER:-data_eng}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password123}
      MYSQL_DATABASE: ${MYSQL_DB:-data_eng}
      PR_ENROLL: ${PR_ENROLL:-true}
      PR_IP_LOC: ${PR_IP_LOC:-127.0.0.1:9091}
      PR_ALIAS: ${PR_ALIAS:-mysql}
      PR_LOC_TGT: ${PR_LOC_TGT:-/prom}
  
  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "exporter:password123@tcp(mysql-db:3306)/data_eng"
  
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./conf/jupyter
        target: /usr/local/bin/before-notebook.d
      - type: bind
        source: ./notebooks
        target: /home/jovyan/work
    environment:
      JUPYTER_PW: ${JUPYTER_PW:-password123}
      GRANT_SUDO: ${JUPYTER_SUDO:-yes}
    user: root